name: Daily Cron Trigger

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Nest.js Daily Task
        run: |
          echo "Disparando cron diário para filmes estreando hoje..."
          RESPONSE=$(curl -s -w "%{http_code}" -o response.json "https://cubos-movies-api.vercel.app/api/v1/webhooks/daily-task")
          HTTP_CODE=$(tail -c 3 <<< "$RESPONSE")

          echo "Resposta HTTP: $HTTP_CODE"
          cat response.json

          if [ "$HTTP_CODE" -ne 200 ]; then
            echo "Erro: Requisição falhou com status $HTTP_CODE"
            exit 1
          fi
