name: Daily Cron Trigger

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Nest.js Endpoint
        run: |
          curl -X GET "https://temp/api/v1/cron/daily-task"
